/* eslint-disable prettier/prettier */
export const OK = '1000';
export const POST_IS_NOT_EXISTED = '9992';
export const CODE_VERIFY_IS_INCORRECT = '9993';
export const NO_DATA_OR_END_OF_LIST_DATA = '9994';
export const USER_IS_NOT_VALIDATED = '9995'; // Không có người dùng này
export const USER_EXISTED = '9996';
export const METHOD_IS_INVALID = '9997';
export const TOKEN_IS_INVALID = '9998';
export const EXCEPTION_ERROR = '9999';
export const CAN_NOT_CONNECT_TO_DB = '1001';
export const PARAMETER_IS_NOT_ENOUGHT = '1002';
export const PARAMETER_TYPE_IS_INVALID = '1003';
export const PARAMETER_VALUE_IS_INVALID = '1004';
export const UNKNOWN_ERROR = '1005';
export const FILE_SIZE_IS_TOO_BIG = '1006';
export const UPLOAD_FILE_FAILED = '1007';
export const MAXIMUM_NUMBER_OF_IMAGES = '1008';
export const NOT_ACCESS = '1009';
export const ACTION_HAS_BEEN_DONE_PREVIOUSLY_BY_THIS_USER = '1010';
